// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmrfykssfejouiqrzbcj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptcmZ5a3NzZmVqb3VpcXJ6YmNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzODIyNTMsImV4cCI6MjA2NDk1ODI1M30.mal81kvvAfNLrwHvuTtpTYERSFo58d1bMgvTf_qO0S4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);